### Create a new Silhouette
POST http://localhost:3000/api/silhouette
Content-Type: application/json

{
  "name": "Air Jordan 1",
  "url": "https://custom-kickz.s3.ap-southeast-1.amazonaws.com/models/air-jordan-1.glb",
  "slug": "air-jordan-1"
}

### Get all Silhouettes
GET http://localhost:3000/api/silhouette

### Get a Silhouette by ID
GET http://localhost:3000/api/silhouette/

### Get a Silhouette by Slug
GET http://localhost:3000/api/silhouette/slug/air-jordan-11-low

### Update a Silhouette by ID
PATCH http://localhost:3000/api/silhouette/685323def63486ce689e95f0
Content-Type: application/json

{
  "metaData": {
    "initialScale": 2.5,
    "unusedMaterials": ["Material.004"]
  }
}

### Delete a Silhouette by ID
DELETE http://localhost:3000/api/silhouette/air-jordan-11-loww
